### ISSUE TITLE
嗨，请问可以添加指定仓库文件路径的功能吗？

### ISSUE THREAD

**Issue by uzvg** [wzk0/picup#1]
指定仓库后，可以指定文件路径，这样就能在将图片上传到同一仓库的不同文件夹。

**Comment by wzk0** [comment]
可以的 只需要执行 picup set github repo xxxxx 就可以了 可以用set设置仓库 用户名等信息



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月9日(周六) 晚上11:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [wzk0/picup] 嗨，请问可以添加指定仓库文件路径的功能吗？ (Issue #1)




 
Closed #1 as completed.

**Comment by wzk0** [comment]
> 指定仓库后，可以指定文件路径，这样就能在将图片上传到同一仓库的不同文件夹。

支持这个功能的 只需`picup 原文件路径 仓库路径+文件名`就ok啦
